name: Eleven
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+3

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  get: ^4.6.1
  provider: ^6.0.2
  share_plus: ^4.0.5


  
  flutter:
    sdk: flutter
    



  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.9
  url_launcher: ^6.1.2
  intl: ^0.17.0
  flutter_launcher_icons: ^0.9.3
  rename: ^2.0.1
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "Assets/11_Icon.png"
  adaptive_icon_foreground: "Assets/11fore.png"




  flutter_lints: ^2.0.1


flutter:


  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

